### ISSUE TITLE
lint for slowest tests

### ISSUE THREAD

**Issue by kmmbvnr** [kmmbvnr/django-jenkins#205]
additional task shows most slowest tests

**Comment by oppianmatt** [comment]
Am I missing something? My jenkins shows the tests and how long each took. And you can sort by the headings.

![tests](https://www.evernote.com/shard/s320/sh/dcb84dfd-3595-4852-8976-0f81638b73db/0664cff6fba7889a2fe6dfcab30b0ba2/deep/0/Pitchup.com--2534-Test-Results--Jenkins-.png)

**Comment by kmmbvnr** [comment]
won't fix
