### ISSUE TITLE
Django Jenkins 0.16.2 is collecting tests outside of  PROJECT_APPS

### ISSUE THREAD

**Issue by mauricioabreu** [kmmbvnr/django-jenkins#221]
I have all my apps located at project/apps/my_apps.
I am facing a problem because Django Jenkins is collecting tests outside of PROJECT_APPS.
I have unit tests and in a folder called scripts but this folder is out of the PROJECT_APPS context. Is it a bug or am I missing something?

Django-Jenkins version: 0.16.2
Django version: 1.6.5
Python version: 2.6

**Comment by asfaltboy** [comment]
@kmmbvnr Can you explain how this was fixed; in which version, or better yet, in which commit?
