### ISSUE TITLE
Is it possible to configure django-jenkins to run tests with nose test runner?

### ISSUE THREAD

**Issue by DariaKnyazeva** [kmmbvnr/django-jenkins#237]
Hi,

I would like to use django-jenkins for generating fancy lint, pep8 etc. reports.
However the tests in a project I work on are supposed to be run with nose test runner - there are a lot of nose attributes and tools embedded in the tests.

Is it possible to configure django-jenkins to run tests with nose test runner?

Thanks!

**Comment by lucianocheng** [comment]
+1

**Comment by torstenfeld** [comment]
+1

**Comment by synic** [comment]
+1

**Comment by kmmbvnr** [comment]
Unfortunately nose project itself is deprecated - https://nose.readthedocs.org/en/latest/#note-to-users
