### ISSUE TITLE
configure PEP8

### ISSUE THREAD

**Issue by Archelyst** [kmmbvnr/django-jenkins#238]
I'm trying to configure the max_line_length for pep8. For that I created a tox.ini and placed it in the project, app and project's parent dir. Also I tried the PEP8_RCFILE = 'tox.ini' option. All with no success. How can I configure this correctly?

**Comment by nwp90** [comment]
It seems that the PYLINT_RCFILE setting is relative to the directory manage.py is in, but that the PEP8_RCFILE setting is relative to whatever was cwd when manage.py was invoked. This is inconsistent and confusing and should be documented (or better, made consistent and then documented).
