### ISSUE TITLE
Enable tests and reports outside applications

### ISSUE THREAD

**Issue by evili** [kmmbvnr/django-jenkins#243]
There should be a mecanism to tell django-jenkins to test/report code outside applications. For example in the project folder.

Say that our project is named `newsite` and it has an application `blog`. I put some code (home views, etc.) in project folder: `newsite/views.py` and  `newsite/tests.py`

In Django 1.6 I "tricked" and put the project folder as if it were an application:

```
PROJECT_APPS = ( 'newsite', 'blog')
```

and it worked.

Now with Django 1.7 the test are run, but it gives an error loading tested locations for the reports. I need to remove project folder from `PROJECT_APPS`.

It would be nice if it could be some way (a setting?) to tell jenkins to test/report code from other non-application folders. Something like:

```
JENKINS_TEST_EXTRA_MODULES= ('newsite.views', 'newsite.forms', )
```

will tell django-jenkins to include these specific modules in reports.

TIA.

Cheers,

 Evili del Rio

**Comment by pifantastic** [comment]
I agree, this would be a very nice addition. We have additional modules that we'd like to test in addition to our Django modules.

**Comment by kmmbvnr** [comment]
won't fix
