### ISSUE TITLE
ImportError: No module named run_jslint

### ISSUE THREAD

**Issue by somepalli** [kmmbvnr/django-jenkins#261]
I am using django 1.5 and django_jenkins 0.14. When i run the 

<h6>python manage.py jenkins</h6>

ImportError: No module named run_jslint

**Comment by lucianocheng** [comment]
Hi @kmmbvnr, would it be possible to update the docs to reflect this change? I think a lot of people are copy/pasting the the JENKINS_TASKS from here:

https://sites.google.com/site/kmmbvnr/home/django-jenkins-tutorial

**Comment by arnaudlamy** [comment]
Yep please update the tutorial ! :)

**Comment by biggihs** [comment]
lol +1 for the tutorial update

**Comment by ogai** [comment]
+1 for tutorial update, and to remove the reference to:
    npm install jshint
in the documentation, in the case `django-jenkins` doesn't support any test on js files anymore, or to document it otherwise.

**Comment by sherbo** [comment]
+1 for tutorial update

**Comment by kmmbvnr** [comment]
any volunteers?

**Comment by mikekeda** [comment]
the tutorial isn't updated yet

**Comment by 0xjame5** [comment]
If no one is up for it I could also do it.

**Comment by HayHiTee** [comment]
Same issue even in the official docs : https://django-jenkins.readthedocs.io/en/latest/
