### ISSUE TITLE
flake8 report in readme says pylint but is pep8

### ISSUE THREAD

**Issue by oppianmatt** [kmmbvnr/django-jenkins#274]
From the readme: Runs flake8 tool over selected Django apps. Creates Pylint compatible report for Jenkins.

But I found it was a pep8 compatible report, not a pylint one. 

And the regex in:

https://github.com/jenkinsci/violations-plugin/blob/master/src/main/java/hudson/plugins/violations/types/pylint/PyLintParser.java#L35

vs

https://github.com/jenkinsci/violations-plugin/blob/master/src/main/java/hudson/plugins/violations/types/pep8/Pep8Parser.java#L41

**Comment by j-san** [comment]
I got screwed +1 !

**Comment by kmmbvnr** [comment]
fixed by @j-san
