### ISSUE TITLE
Extra arguments not passed to test runner since Django 1.8

### ISSUE THREAD

**Issue by unklphil** [kmmbvnr/django-jenkins#281]
Django 1.8 uses `argparse.ArgumentParser` and [has changed the method to add custom arguments to the test management command](https://docs.djangoproject.com/en/1.8/releases/1.8/#custom-test-management-command-arguments-through-test-runner).

For example, we used to use this command: `python manage.py jenkins --noinput --enable-coverage` but now it complains that `manage.py: error: no such option: --noinput`

**Comment by kmmbvnr** [comment]
Did you try git version?

**Comment by unklphil** [comment]
Wow, quick response! Will try it out, thanks.
