### ISSUE TITLE
Warning about django.utils.importlib removed in Django 1.9

### ISSUE THREAD

**Issue by cacarrara** [kmmbvnr/django-jenkins#283]
After upgrading from Django 1.7 to Django 1.8 I get the following warning:
```
/django_jenkins/tasks/with_coverage.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
from django.utils.importlib import import_module
```

**Comment by jspitzen** [comment]
Duplicate of #271 I think

**Comment by cacarrara** [comment]
You're correct. Sorry my mistake. Any plan to next release with the fix?

**Comment by kmmbvnr** [comment]
As usual at 15th day of the Month )

**Comment by grey0ne** [comment]
Is there any chance to get this warning removed again?

**Comment by abramovtv** [comment]
Bug is still there
