### ISSUE TITLE
Pep8 and PyLint not exclude the migrations folder

### ISSUE THREAD

**Issue by LuizPeroso** [kmmbvnr/django-jenkins#286]
I´m runnig the jenkins command with this command line:

python manage.py jenkins --enable-coverage --coverage-exclude=COVERAGE_EXCLUDES_FOLDERS --pep8-ignore=COVERAGE_EXCLUDES_FOLDERS

But it isn´t exclude the migrations folder:
Test result:

pep8:

hce/migrations/0001_initial.py	0	8	0	8
campanhas/migrations/0003_regraacumulo.py	0	7	0	7
campanhas/migrations/0018_auto_20150114_2044.py	0	5	0	5
campanhas/migrations/0011_auto_20150114_1955.py	0	5	0	5
contas/migrations/0001_initial.py	0	4	0	4
hce/migrations/0003_settinghce.py	0	4	0	4
produtos/migrations/0010_auto_20150109_1345.py	0	4	0	4
campanhas/migrations/0010_auto_20150114_1951.py	0	4	0	4
carteiras/migrations/0006_auto_20150131_1643.py	0	3	0	3
campanhas/migrations/0012_auto_20150114_1957.py	0	3	0	3
estabelecimentos/migrations/0001_initial.py	0	3	0	3
participantes/migrations/0001_initial.py	0	3	0	3
participantes/migrations/0003_auto_20150207_1345.py	0	3	0	3
participantes/migrations/0006_auto_20150207_1626.py	0	3	0	3
produtos/migrations/0001_initial.py	0	3	0	3
produtos/migrations/0006_auto_20150109_1330.py	0	3	0	3
empresas/tests.py	0	3	0	3 (+3)
campanhas/migrations/0008_auto_20150114_1817.py	0	2	0	2
campanhas/migrations/0019_auto_20150116_1334.py	0	2	0	2
campanhas/migrations/0026_auto_20150305_1712.py	0	2	0	2
campanhas/migrations/0027_auto_20150320_1754.py	0	2	0	2
participantes/migrations/0005_auto_20150207_1626.py	0	2	0	2
participantes/migrations/0007_auto_20150207_1631.py	0	2	0	2
participantes/migrations/0008_auto_20150207_1633.py	0	2	0	2
participantes/migrations/0009_auto_20150208_1510.py	0	2	0	2
participantes/migrations/0010_auto_20150208_1512.py	0	2	0	2
participantes/migrations/0011_auto_20150208_1513.py	0	2	0	2
participantes/migrations/0012_auto_20150208_1513.py	0	2	0	2
participantes/migrations/0013_auto_20150208_1514.py	0	2	0	2
participantes/migrations/0014_auto_20150208_1515.py	0	2	0	2
participantes/migrations/0015_auto_20150208_1515.py	0	2	0	2
produtos/migrations/0016_auto_20150114_1648.py	0	2	0	2
produtos/migrations/0020_auto_20150114_1711.py	0	2	0	2
transacoes/migrations/0001_initial.py	0	2	0	2
transacoes/migrations/0003_auto_20150326_1103.py	0	2	0	2
contas/migrations/0005_contacorrente_participante.py	0	1	0	1
campanhas/migrations/0001_initial.py	0	1	0	1
campanhas/migrations/0014_regraacumulo_periodo.py	0	1	0	1
campanhas/migrations/0016_periodo_regra_acumulo.py	0	1	0	1
campanhas/migrations/0021_auto_20150126_1702.py	0	1	0	1
campanhas/migrations/0023_regraacumulo_participantes.py	0	1	0	1
campanhas/migrations/0024_auto_20150129_1643.py	0	1	0	1
campanhas/migrations/0029_remove_regraacumulo_texto_descricao.py	0	1	0	1
carteiras/migrations/0008_comprovante_carteira.py	0	1	0	1
carteiras/migrations/0012_auto_20150313_1458.py	0	1	0	1
campanhas/migrations/0005_regraacumulo_calculo.py	0	1	0	1
contas/migrations/0007_auto_20150305_1712.py	0	1	0	1
empresas/api.py	0	1	0	1 (+1)
empresas/migrations/0001_initial.py	0	1	0	1
hce/migrations/0004_auto_20150208_1243.py	0	1	0	1
operadores/migrations/0001_initial.py	0	1	0	1
operadores/migrations/0002_auto_20150129_1642.py	0	1	0	1
usuarios/migrations/0001_initial.py	0	1	0	1
usuarios/migrations/0002_auto_20141219_1727.py	0	1	0	1
usuarios/migrations/0004_auto_20141223_1511.py

pylint:

transacoes/api.py	0	103	3	106
relatorios/api.py	0	56	6	62
hce/api.py	1	47	7	55
carteiras/api.py	4	41	0	45
campanhas/api.py	0	37	4	41
campanhas/motor_regras.py	1	36	0	37
usuarios/api.py	0	33	1	34
contas/api.py	3	22	2	27
participantes/api.py	0	24	2	26
produtos/api.py	0	24	2	26
estabelecimentos/api.py	0	23	1	24
aut/api.py	0	18	2	20
empresas/api.py	1	14	3	18
operadores/api.py	0	11	0	11
relatorios/migrations/__init__.py	0	10	0	10
produtos/tests.py	0	7	2	9
empresas/tests.py	3	5	0	8
campanhas/tests/test_motor_regras.py	0	5	2	7
estabelecimentos/tests.py	0	6	1	7
campanhas/tests/__init__.py	0	4	2	6
campanhas/migrations/0003_regraacumulo.py	1	2	2	5
campanhas/tests/test_model.py	0	5	0	5
participantes/tests.py	0	2	2	4
aut/admin.py	0	2	1	3
aut/models.py	0	1	1	2
aut/tests.py	0	1	1	2
campanhas/migrations/0004_remove_regraacumulo_calculo.py	0	1	1	2
campanhas/migrations/0006_remove_regraacumulo_premio.py	0	1	1	2
campanhas/migrations/0009_auto_20150114_1837.py	0	1	1	2
campanhas/migrations/0013_remove_regraacumulo_periodo.py	0	1	1	2
campanhas/migrations/0015_remove_regraacumulo_periodo.py	0	1	1	2
campanhas/migrations/0020_auto_20150116_1402.py	0	1	1	2
campanhas/migrations/0028_remove_regraacumulo_quantidade_compra_acumulativo.py	0	1	1	2
campanhas/migrations/0029_remove_regraacumulo_texto_descricao.py	0	1	1	2
campanhas/views.py	0	1	1	2
carteiras/migrations/0003_auto_20150130_1607.py	0	1	1	2
carteiras/migrations/0007_remove_comprovante_carteira.py	0	1	1	2
carteiras/migrations/0009_remove_comprovante_transacao.py	0	1	1	2
carteiras/tests.py	0	1	1	2
carteiras/views.py	0	1	1	2
contas/migrations/0003_remove_contacorrente_transacao.py	0	1	1	2
contas/migrations/0008_remove_contacorrente_transacao.py	0	1	1	2
contas/models.py	0	1	1	2
contas/tests.py	0	1	1	2
contas/views.py	0	1	1	2
empresas/migrations/0002_remove_empresa_data_inicio.py	0	1	1	2
empresas/views.py	0	1	1	2
estabelecimentos/views.py	0	1	1	2
hce/models.py	0	0	2	2
operadores/tests.py	0	1	1	2
operadores/views.py	0	1	1	2
participantes/models.py	0	1	1	2
participantes/views.py	0	1	1	2
produtos/migrations/0004_auto_20150107_1838.py	0	1	1	2
produtos/migrations/0005_auto_20150109_1321.py	0	1	1	2
produtos/migrations/0007_auto_20150109_1337.py	0	1	1	2
produtos/migrations/0008_auto_20150109_1343.py	0	1	1	2
produtos/migrations/0012_auto_20150114_1631.py	0	1	1	2
produtos/migrations/0014_remove_categoria_dominio.py	0	1	1	2
produtos/migrations/0017_auto_20150114_1656.py	0	1	1	2
produtos/migrations/0018_auto_20150114_1658.py	0	1	1	2
produtos/migrations/0019_auto_20150114_1700.py	0	1	1	2
produtos/migrations/0021_remove_produto_estabelecimento.py	0	1	1	2
produtos/views.py	0	1	1	2
relatorios/admin.py	0	1	1	2
relatorios/models.py	0	1	1	2
relatorios/tests.py	0	1	1	2
relatorios/views.py	0	1	1	2
transacoes/migrations/0002_auto_20150126_1702.py	0	1	1	2
transacoes/views.py	0	1	1	2
usuarios/tests.py	0	1	1	2
usuarios/views.py	0	1	1	2
campanhas/migrations/0008_auto_20150114_1817.py	1	0	0	1
campanhas/migrations/0010_auto_20150114_1951.py	1	0	0	1
campanhas/migrations/0027_auto_20150320_1754.py	1	0	0	1
campanhas/models.py	0	0	1	1
carteiras/models.py	0	1	0	1
operadores/models.py	0	0	1	1
usuarios/models.py

**Comment by kmmbvnr** [comment]
By providing command line option, you are complete overrides default behavior.
