### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by keradus** [kmmbvnr/django-jenkins#289]
any chances to get stable release?

**Comment by kmmbvnr** [comment]
There is only few deprecation changes in master, no functional differens between released version on pypi.

**Comment by keradus** [comment]
from https://pypi.python.org/pypi/django-jenkins/ : 
Development Status :: 4 - Beta

Also, released version is < 1.0

That is why I ask for a stable version. Not becouse of that few changes on master.

**Comment by kmmbvnr** [comment]
The letters and digits means nothing anyway ) 

The software just works on not. django-jenkins obviously works. It is software a project with 5 years history and 1k downloads per day.

**Comment by keradus** [comment]
Yeah, it works. And for that it would be great to finally have stable release.
What is the problem to release it as stable, not beta ?
