### ISSUE TITLE
README should mention python/django compatibility

### ISSUE THREAD

**Issue by asfaltboy** [kmmbvnr/django-jenkins#293]
I just tried upgrading `django-jenkins` from my old version (0.14.1) to release 0.16.3, and encountered an import error.

The module I'm missing, `django.test.runner`, was [only added in Django 1.6](https://github.com/django/django/commit/9012833af857e081b515ce760685b157638efcef), so any Django > 1.6 therefore cannot be (easily?) supported.

I suggest mentioning Django/Python versions supported (and the reasoning behind dropped/omitted versions) for easier upgrades/changes. I just realized I can look in `tox.ini` for what is tested, but still, would be nice if it was explained in the documentation.

**Comment by kmmbvnr** [comment]
Yep, PR is welcome.

Currently  this is mentioned in setup.py only
