### ISSUE TITLE
importlib and unittest deprecation warnings

### ISSUE THREAD

**Issue by adrian17** [kmmbvnr/django-jenkins#294]
On the current HEAD (0166ae25fdd96b3cf606b44c5f2aaa1ad4156ad0) I still see these warnings:

    /local/lib/python2.7/site-packages/django_jenkins/tasks/with_coverage.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
       from django.utils.importlib import import_module

    /local/lib/python2.7/site-packages/django_jenkins/runner.py:10: RemovedInDjango19Warning: django.utils.unittest will be removed in Django 1.9.
       from django.utils.unittest import TextTestResult, TextTestRunner

**Comment by kmmbvnr** [comment]
Duplicate
