### ISSUE TITLE
0.17.0 not tagged

### ISSUE THREAD

**Issue by asedeno** [kmmbvnr/django-jenkins#295]
The 0.17.0 release was not tagged, or the tag was not pushed to this repo. Could you please fix that?

**Comment by kmmbvnr** [comment]
I just wonder. Why you need that?

**Comment by asedeno** [comment]
https://github.com/kmmbvnr/django-jenkins/tags should really list the current version. I should not have to guess which commit was released as 0.17.0. I can, and have, figured it out, but that doesn't mean it and future releases should not be tagged.

**Comment by kmmbvnr** [comment]
That's not an answer why you personally need  the tags.

Releases stored on pypi.

**Comment by asedeno** [comment]
I'm sorry, what? Tags are generally useful and not having the latest release tagged when you have a lot of other releases tagged makes this repository look like it's not the right one.

I want it tagged because it makes it easier for me to work on a fork off of 0.17.0 while I wait for a new release that actually silences the django 1.9 deprecation warnings. I honestly did not think I would have to justify tagging releases in a git project. It's best practice, and trivial effort.

**Comment by nikolas2** [comment]
@kmmbvnr I agree, tags are useful! Please re-open.

**Comment by asedeno** [comment]
FYI, @nikolas2, I ditched django-jenkins from my projects when @kmmbvnr closed this bug without tagging releases, and it made my life that much better.
