### ISSUE TITLE
Errors with coverage 4.0

### ISSUE THREAD

**Issue by jproffitt** [kmmbvnr/django-jenkins#298]
Coverage 4.0 is still in beta, but django-jenkins will not work with it. See http://coverage.readthedocs.org/en/latest/changes.html#version-4-0b2-pre-release-22-august-2015 for backward incompatibilities.

In particular, the `'_harvest_data'` attribute. I am getting this error:

    File ".../site-packages/django_jenkins/tasks/with_coverage.py",> line 34, in save
        self.coverage._harvest_data()
    AttributeError: 'Coverage' object has no attribute '_harvest_data'

**Comment by mrafieee** [comment]
I faced this as well I try installing it using pip,
it seems this change has brought some incompatibilities

coverage (4.0.1)
Django (1.8)
pep8 (1.6.2)
django-jenkins (0.17.0)
pyflakes (1.0.0)

**Comment by mrafieee** [comment]
I downgraded Coverage to 4.0 but it did not work !!

**Comment by grippon** [comment]
Anybody reading that, I upgraded django-jenkins to 0.18.0 and it seems to work.
