### ISSUE TITLE
possible compatibility issue with Django 1.9

### ISSUE THREAD

**Issue by jeroenjacobs1205** [kmmbvnr/django-jenkins#302]
Using django-jenkins with Django 1.8 results in the following warning:

    django.utils.deprecation.RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.

The following file seems to be cause:
django-jenkins/django_jenkins/tasks/with_coverage.py

I guess the following statement:

    from django.utils.importlib import import_module

needs to be changed to:

    from importlib import import_module

**Comment by kmmbvnr** [comment]
Duplicate
