### ISSUE TITLE
Release tags for 0.16.4 and 0.17 are missing

### ISSUE THREAD

**Issue by wulmer** [kmmbvnr/django-jenkins#303]
Hi, thanks for this nice tool. I wanted to update my 0.16.3 to the latest version but noticed, that you haven't set tags for the latest releases. Could you please tag the relevant commits? Thanks!

**Comment by nikolas2** [comment]
@wulmer it looks like 0.16.4 was released at this commit: https://github.com/kmmbvnr/django-jenkins/commit/eb296466c2475f7e75a663dd46548a5bd67180a0

And 0.17.0 was released here: https://github.com/kmmbvnr/django-jenkins/commit/8837e52aa3156254e940c22d780c3ede6754680a

**Comment by wulmer** [comment]
@nikolas2 Thanks. Would still be nice to have the tags set...

**Comment by nikolas2** [comment]
Yeah.. i agree. @kmmbvnr ? If you need help maintaining this package I could help.
