### ISSUE TITLE
Flake8 test broken with flake8 >=2.5.0

### ISSUE THREAD

**Issue by timsavage** [kmmbvnr/django-jenkins#319]
Am getting the following error:
```
File "django_jenkins/tasks/run_flake8.py", line 98, in run
    pep8style.input_dir(os.path.relpath(location))
AttributeError: 'StyleGuide' object has no attribute 'input_dir'
```
I've taken a quick look into the issue and in the 2.5 release of flake8 the class flake8.engine.StyleGuide is now a wrapper around the pep8.StyleGuide rather than a sub class of which the input_dir method is not implemented by the wrapper.

The simple workaround for now is to install flake8<2.5.0

**Comment by timsavage** [comment]
Reference to diff in flake8

https://gitlab.com/pycqa/flake8/compare/3ce1050d0fd0fe8c2cafb8c62b4a37b58f3b4c57...master#901c1818b558f5b2b2b70537b40f38067f7f9974_84_110

**Comment by kmmbvnr** [comment]
Pull requests with better fix are welcome.
