### ISSUE TITLE
Doesn't work with django_nose on Django 1.8+

### ISSUE THREAD

**Issue by mic159** [kmmbvnr/django-jenkins#324]
Currently, when trying to run the `./manage.py jenkins` command, it gets this error:

```
argparse.ArgumentError: argument -l/--debug: conflicting option string(s): --debug
```

Because both `django_nose` and `django_jenkins` define a `--debug` option.

```
django-jenkins==0.18.0
django-nose==1.4.3
```

**Comment by kmmbvnr** [comment]
nose is not supported
