### ISSUE TITLE
Improve changelog

### ISSUE THREAD

**Issue by darkowic** [kmmbvnr/django-jenkins#325]
Please add changelog with notes from older versions. I was trying to upgrade django jenkins from 1.6 to 1.8 and I lose my time only because the documentation doesn't contain anything about older version.

**Comment by kmmbvnr** [comment]
There is full changelog, in the usual full changelog place - https://github.com/kmmbvnr/django-jenkins/blob/master/CHANGELOG.rst

**Comment by darkowic** [comment]
:+1: 
Oh then I'm sorry for problem... I didn't found it. Maybe add link in readme :)

**Comment by kmmbvnr** [comment]
pull requests are welcome
