### ISSUE TITLE
Problem running pylint on windows

### ISSUE THREAD

**Issue by giusepanzuto** [kmmbvnr/django-jenkins#329]
Hi, the file django_jenkins\tasks\pylint.rc give some error when executing on windows enviroment.
at the end of line 18 the word object is surrounded with special double quote, that brake the config parser with this error : 

  File "C:\Program Files\Python35\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 969: character maps to undefined

please change with double quote char "

thank you
Giuseppe

**Comment by kmmbvnr** [comment]
Thank you.

TIll new release you can solve the issue by specify custom `pylint.rc` location in the PYLINT_RCFILE settings.
