### ISSUE TITLE
 RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead

### ISSUE THREAD

**Issue by kramarz** [kmmbvnr/django-jenkins#330]
Remove code which is already commented to be removed
https://github.com/kmmbvnr/django-jenkins/blob/master/django_jenkins/management/commands/jenkins.py#L31

**Comment by kmmbvnr** [comment]
It would be removed as soon as django 1.7 will not be supported by django team

**Comment by kmmbvnr** [comment]
pull request is welcome

**Comment by kramarz** [comment]
Thank you.
