### ISSUE TITLE
Enable add_arguments on the runners to work

### ISSUE THREAD

**Issue by batiste** [kmmbvnr/django-jenkins#335]
A example is worth a thousand words. I would like to be able to use what is described in the Django documentation here about add_arguments(cls, parser):

https://docs.djangoproject.com/en/1.9/topics/testing/advanced/#django.test.runner.DiscoverRunner

```
from django_jenkins.runner import CITestSuiteRunner
import unittest

class DummyRunner(CITestSuiteRunner):

    def __init__(self, func=False, **kwargs):
        self.run_functionnal = func
        super(DummyRunner, self).__init__(**kwargs)

    def run_suite(self, suite, **kwargs):
        new_suite = []

        if not self.run_functionnal:
            for test in suite:
                if getattr(test, 'static_handler', None) is None:
                    new_suite.append(test)
        else:
            new_suite = suite

        return super(CITestSuiteRunner, self).run_suite(
            unittest.TestSuite(new_suite), **kwargs)

   @classmethod
    def add_arguments(self, parser):
        parser.add_argument('--func', default=False, help='Enable functionnal test')

```

Then I would like to run

`python manage.py jenkins --func=yes`

**Comment by kmmbvnr** [comment]
Yep, you need to extend https://github.com/kmmbvnr/django-jenkins/blob/master/django_jenkins/management/commands/jenkins.py#L42

Waiting for PR.

**Comment by batiste** [comment]
Oki I understand why this is not working: Django extends the Command using what is defined by the TEST_RUNNER config here:

https://github.com/django/django/blob/master/django/core/management/commands/test.py#L56

But not by what is defined by the JENKINS_TASK_RUNNER. So the add_arguments on my class has no effect. How would propose we fix this?

**Comment by batiste** [comment]
I think my PR is working and is a decent solution. Do you need tests for this?

https://github.com/kmmbvnr/django-jenkins/pull/336

**Comment by batiste** [comment]
Actually this is just wrong> Now I am running into troubles if I do this:

JENKINS_TEST_RUNNER = 'lib.runner.TestRunner'
TEST_RUNNER = 'lib.runner.TestRunner'

The arguments are now added twice and it triggers an error it get the argument

argparse.ArgumentError: argument --run-functionnal: conflicting option string(s): --run-functionnal

**Comment by batiste** [comment]
Oki so now my runner looks like that 

`class TestRunner(CITestSuiteRunner):

    def __init__(self, run_functionnal=False, **kwargs):
        self.run_functionnal = run_functionnal
        super(TestRunner, self).__init__(**kwargs)

    def run_suite(self, suite, **kwargs):
        new_suite = []

        if not self.run_functionnal:
            for test in suite:
                if getattr(test, 'static_handler', None) is None:
                    new_suite.append(test)
        else:
            new_suite = suite

        return super(CITestSuiteRunner, self).run_suite(
            unittest.TestSuite(new_suite), **kwargs)

    @classmethod
    def add_arguments(self, parser):
        try:
            parser.add_argument('--run-functionnal',
                action='store_true', help='Run functionnal tests')
            super(CITestSuiteRunner, self).add_arguments(parser)
        except argparse.ArgumentError:
            pass
`

With those settings

```
JENKINS_TEST_RUNNER = 'lib.runner.TestRunner'
TEST_RUNNER = 'lib.runner.TestRunner'

```
And it seems to work again both with python manage.py test and python manage.py jenkins

But this his convoluted
