### ISSUE TITLE
Coverage report isn't generated when the test fails

### ISSUE THREAD

**Issue by lucasgm-bt** [kmmbvnr/django-jenkins#338]
When I run the following command and the unit tests fails, the coverage, flake8 and pylint reports are not generated (only junit.xml is generated). If the tests pass, all reports are generated.

`python3 manage.py jenkins --enable-coverage --settings=settings.test`

If I manually run the tool (e.g. coverage), the reports are generated, regardless of the test result 

```
coverage run --source='.' manage.py jenkins --settings=settings.test
coverage xml -o reports/coverage.xml
```

I'm using django-jenkins 0.18.1, Django 1.9.7 and my settings looks like:

```
...

INSTALLED_APPS += [ 'django_jenkins' ]

JENKINS_TASKS = (
   'django_jenkins.tasks.run_pylint',
   'django_jenkins.tasks.run_flake8'
)

...
```

Is it a bug?

**Comment by kmmbvnr** [comment]
That's correct. If unit tests failed the total build considered failed anyway
