### ISSUE TITLE
Move tutorial to something like ReadTheDocs so anyone can contribute

### ISSUE THREAD

**Issue by GabLeRoux** [kmmbvnr/django-jenkins#349]
> For more details see the generic tutorial: https://sites.google.com/site/kmmbvnr/home/django-jenkins-tutorial

I'd like to edit this as I found a typo:
> add `django_jenins` to `INSTALLED_APPS` in `settings.py`

Would be

> add `django_jenkins` to `INSTALLED_APPS` in `settings.py`

> Add to you project file named requirements.pip with all project dependencies list

Would be

> Add to your project `requirements.txt` with all project dependencies list

etc.

If you add me to contributors, I could find the time to set this up in Read The Docs and convert the google document.

I'd be really happy to give a hand as this project is very handy :)

I've created https://readthedocs.org/projects/django-jenkins/ and added kmmbvnr as a maintainer.

> This repository doesn't have a valid webhook set up. That means it won't be rebuilt on commits to the repository. 
> You can resync your webhook to fix this.

**Comment by GabLeRoux** [comment]
@kmmbvnr bump :icecream:

**Comment by kmmbvnr** [comment]
Sorry, I don't think that the ReadTheDocs website is well suited for the things like tutorials.

Thanks for notes. I made few changes in the google docs.

**Comment by GabLeRoux** [comment]
Our opinions differ here.
I think it's not possible to collaborate on the google docs easily unless you provide specific access to some people directly. I consider that a tutorial is only a section of the documentation. I personally didn't see the link to the google docs at first so I was very confused and I find read the docs more convenient and clean.

* Easier to collaborate, everybody can suggest a PR
* We can keep track of the modifications
* There's a table of content! :)
* We can add more documentation (easily)

It could also be some markdown in a folder in the project or a wiki on Github. I recommended read the docs based on the fact that many python projects use it.
My main concern was collaboration here

**Comment by SalahAdDin** [comment]
Please, more documentation!

**Comment by GabLeRoux** [comment]
@kmmbvnr can you reconsider this with #351 ? I still think this would be a good improvement to the project and it would make it more accessible for anyone.

If you think rtfd is not the right solution here, let me know why and what we could do to get this merged. I'm always looking for ways to improve myself as a developer and I'd like to know what went wrong here.
I know it's been a while, but I really like this project and I feel like more documentation can't hurt.
Thanks for your time

**Comment by nikolas** [comment]
I agree, django-jenkins should use Sphinx / readthedocs for all documentation as it's standard for python projects. It allows for collaboration and keeps the documentation close to the code.
