### ISSUE TITLE
Simplify use of cloc instead of sloccount.

### ISSUE THREAD

**Issue by adrianboyko** [kmmbvnr/django-jenkins#353]
The sloccount plugin for Jenkins can process output from either sloccount or cloc. Since cloc supports more languages (e.g. I'm writing front-end code in Elm) it would be helpful to have an easy way to choose cloc. What would be the most sensible way to make this possible in django-jenkins? Add a django_jenkins.tasks.run_cloc task?

**Comment by kmmbvnr** [comment]
I think it's better to use the tool without django-jenkins wrapper.

The reason for the sloccount task was an idea to filter south migrations bloated with thousands of lines of code.

Today, for built-in django migrations are pretty small and don't increase sloc counters a lot.

So, I removed the sloccount task from django-jenkins.
