### ISSUE TITLE
Coverage only runs if --enable-coverage is present in command line

### ISSUE THREAD

**Issue by samupl** [kmmbvnr/django-jenkins#354]
According to https://github.com/kmmbvnr/django-jenkins/blob/master/django_jenkins/apps.py#L17 - coverage is only run if `--enable-coverage` is present in the `sys.argv` list. However, it seems to counter the possibility to run manage.py tasks directly from the code.

For example, I have a minimal django package and a very minimal django project that's supposed only to run init tests. The settings file is called `run_tests.py` and the bottom of it states:

```python
if __name__ == '__main__':
    # set the ENV
    sys.path.append(os.path.join(BASE_DIR, 'src'))
    os.environ['DJANGO_SETTINGS_MODULE'] = 'src.minimal_django_project'

    from django.core import management

    # Execute jenkins task directly
    management.execute_from_command_line(
       [__file__, 'jenkins', '--enable-coverage', 'mypackage']
    )
```

However, `sys.argv` is empty. The way django handles this by default is to check for `sys.argv` if any are present:

```python
class ManagementUtility(object):
    """
    Encapsulates the logic of the django-admin and manage.py utilities.

    A ManagementUtility has a number of commands, which can be manipulated
    by editing the self.commands dictionary.
    """
    def __init__(self, argv=None):
        self.argv = argv or sys.argv[:]
        self.prog_name = os.path.basename(self.argv[0])
        self.settings_exception = None
```

This is not a critical bug, but something that could be thought of in future releases.

**Comment by kmmbvnr** [comment]
I don't think that it could be fixed.

The reason for that is to cover `models.py` in django 1.7+. We need to start coverage very early, on an application initialisation, even before the args passed to the management.command  are parsed.

You can just add  `sys.args += ['--enable-coverage']` to your script.
