### ISSUE TITLE
pip installing fails with python2.7

### ISSUE THREAD

**Issue by DanielKN** [kmmbvnr/django-jenkins#362]
If django-jenkins is pip installed on its own, the setup.py will pull in django v.2.0, which will result in the following error in a python2.7 environment. 

see: https://code.djangoproject.com/ticket/28878

(pip version 9.0.1)
`pip install django-jenkins`

Stacktrace:

```
Collecting django-jenkins
  Downloading django_jenkins-0.110.0-py2.py3-none-any.whl
Collecting Django>=1.8 (from django-jenkins)
  Downloading Django-2.0.tar.gz (8.0MB)
    100% |████████████████████████████████| 8.0MB 6.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NCKqyN/Django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
```

Although in most cases, django is already installed to the desired version, this error won't occur.

**Comment by kmmbvnr** [comment]
django 2.0 have no python 2.7 support. It's not django-jenkins problem

**Comment by DanielKN** [comment]
Sorry, I more meant that django-jenkins setup.py could ensure that it doesn't pull in incompatible versions if django, e.g if its python2.7 env,  pin it between 1.8 -1.11,  Is there a downside to adding this to the setup.py?
