### ISSUE TITLE
Support for coverage for parallel tasks 

### ISSUE THREAD

**Issue by kmmbvnr** [kmmbvnr/django-jenkins#8]
Allow to configure in hudson downstream builds, and covers it results

**Comment by rknLA** [comment]
I just discovered that my coverage reports were dramatically wrong after someone added added a `--parallel` flag to our target.. I'd love to see this supported if it's still possible.

**Comment by SalahAdDin** [comment]
@kmmbvnr @rknLA needs it.

**Comment by mounirmesselmeni** [comment]
@kmmbvnr I think this is an important feature sincerely for many people.
